export const quizQuestions = {
  1: "Are you more forgetful than usual—losing things, missing appointments, or forgetting what you are doing or saying?",
  2: "Are you depressed for no apparent reason? Have you lost motivation and interest in things you used to enjoy?",
  3: "Are you more anxious or worried than usual? Do you get anxiety or panic attacks or feel a general, constant sense of unease or foreboding?",
  4: "Do you have “brain fog,” or more difficulty concentrating and focusing or staying with one task to completion than usual?",
  5: "Do you experience unexplained mood swings?",
  6: "Do you say words you don’t mean to say, or call things by the wrong name, and notice only after you say it or when someone else points it out?",
  7: "Do you have sensory issues—i.e., are you experiencing sound, light, or touch in a different way than is normal for you?",
  8: "Have you been diagnosed with (or do you suspect you have) mild cognitive decline, and/or do you have a family history of dementia, such as Alzheimer’s disease?",
  9: "Are you often bloated or gassy, and/or does your stomach get distended after or between meals, so that you look pregnant?",
  10: "Do you have diarrhea or loose, watery stool that is difficult to control or comes on suddenly?",
  11: "Do you get constipated, or go more than twenty-four hours without having a bowel movement, or do you have hard, dry stool that is difficult to pass, resembling small pellets?",
  12: "Do you have alternating diarrhea and constipation more often than normal (firm but soft and easy to pass) stools?",
  13: "Do you get heartburn or acid reflux after eating, when you’ve gone too long without eating, and/or at night?",
  14: "Is your tongue covered with a fuzzy-looking coating, and/or do you have chronic bad breath even when you practice good oral hygiene?",
  15: "Does your stomach hurt or cramp, or do you feel sick or nauseated, after eating, whether or not you can associate this with any particular food?",
  16: "Do you get uncomfortable stomach or other gastric symptoms (like gas, bloating, or diarrhea) when you are experiencing extreme emotions, such as nervousness, fear, or anxiety?",
  17: "Do you retain water easily, and/or feel like your body looks much larger on some days and much smaller and tighter on other days, in a way too extreme or sudden to be related to fat gain or loss? If you press your finger into your lower leg, does it leave a pit for a few seconds?",
  18: "Does your weight fluctuate more than five pounds from morning to evening or from one day to the next?",
  19: "Have you been diagnosed with any chronic infections such as mold toxicity, Lyme disease, or viral infection?",
  20: "Do you have a vague feeling of “being toxic,” even if you can’t pin it on any particular symptom?",
  21: "Have you noticed a yellowish tint to your skin or the whites of your eyes?",
  22: "Do you have abdominal tenderness that seems unrelated to eating, especially in the upper right quadrant of your torso, or that spreads to your upper back or shoulder?",
  23: "Does your urine tend to be dark yellow, and/or does your stool tend to float?",
  24: "Do you have unexplained itching, flaking, or rashes on your hands and/or feet?",
  25: "Do you crave sugary or starchy foods even when you have already eaten enough or feel full (such as after a big meal or too soon between meals)?",
  26: "Have you noticed an increase in appetite and/or thirst and urination recently?",
  27: "Do you get blurred vision that comes and goes?",
  28: "Are you unusually tired even if you got enough sleep but notice that your fatigue is relieved by eating something?",
  29: "Do you feel light-headed, dizzy, shaky, jittery, irritable, or “hangry” (a combination of hungry and angry) when you haven’t eaten for a few hours or you skip a meal?",
  30: "Is your waist girth equal to or greater than your hip girth?",
  31: "Do you have difficulty losing weight, even when cutting calories and/or exercising?",
  32: "Have you had your fasting blood sugar tested and it was 100 dl/ml or higher, and/or have you had a hemoglobin A1C test and it was 5.7 or above, and/or do you have a diagnosis of prediabetes, metabolic syndrome, or type 2 diabetes?",
  33: "Do you tend to have fatigue and/or headaches in the afternoons, then get a second wind in the evening, which causes you to stay up late?",
  34: "Do you feel dizzy when you stand up suddenly?",
  35: "Do you often crave salty foods?",
  36: "Are your hands and feet often cold, even when your environment is warm?",
  37: "Do you sleep excessively, or feel as if you could sleep all day and still sleep at night?",
  38: "Are the outer thirds of your eyebrows thinning or missing?",
  39: "Has your sex drive disappeared? Are you rarely if ever “in the mood?",
  40: "For women: Are you experiencing irregular, painful, or unusually heavy menstrual periods? For men: Have you recently experienced any new occurrence of erectile dysfunction?",
  41: "Do your joints hurt periodically, constantly, or in flares, in random places, with the pain coming and going, seemingly unrelated to injuries?",
  42: "Are you hypermobile, “double-jointed,” or are your joints hyper-flexible?",
  43: "Are you accident-prone, often twisting your ankle, tripping or falling, or dropping things? Do you consider yourself clumsy? Do you often injure your tendons and/or ligaments?",
  44: "Do your joints constantly pop, crack, snap, or get stuck in certain positions?",
  45: "Do you wake up with stiff and/or aching joints and/or muscles but can relieve the stiffness by movement, only to find that it returns at the end of an active day?",
  46: "Do you have chronic neck or back pain, tightness, and tension?",
  47: "Do you get pins and needles, random stabbing pains, and/or numbness in your hands and feet, or shooting pains down your arms or legs?",
  48: "Are massages painful, especially in your arms, legs, and buttocks?",
  49: "Are you experiencing obvious extreme reactions to certain foods or after eating—reactions such as vomiting, diarrhea, pain, skin reactions, or neurological episodes like brain fog or panic attacks?",
  50: "Are you intolerant to cold or heat, and/or do your hands or feet turn bluish or gray when they are cold? And/or are your skin, mouth, or eyes unusually dry?",
  51: "Do you have a family history of autoimmune issues, such as rheumatoid arthritis, lupus, multiple sclerosis, celiac disease, inflammatory bowel disease/Crohn’s disease, or Hashimoto’s thyroiditis?",
  52: "Do you have joint pain and swelling, and/or numbness and tingling, bilaterally (in the same place on both sides of your body, such as in both hands, elbows, knees, and/or feet)?",
  53: "Do you have unexplained rashes, chronic acne, or recurring boils or cystic acne on your face or body?",
  54: "Do you have extreme, constant, unrelenting fatigue that cannot be relieved by sleeping, eating, or other remedies?",
  55: "Are you having unexplained muscle weakness, or have you noticed that your foot is dragging or you are dropping things more often?",
  56: "Are any of the above symptoms episodic, flaring up, sometimes to an extreme degree, then dying down for a while, only to return days, weeks, or even months later?"
}
 export const quizQuestionSpanish = {
  1: "Se te olvidan las cosas más de lo usual—pierdes cosas, se te olvidan tus reuniones, o se te olvida de que estabas hablando?",
  2: "Te sientes deprimida sin ninguna razón? Has perdido motivación e interés en cosas que antes disfrutabas?",
  3: "Estas más ansiosa que lo usual? Tienes ataques de pánico o ansiedad?",
  4: 'Tienes "nubla mental", o se te hace difícil concentrarte y enfocarte en una tarea más de lo usual?',
  5: "Tienes cambios de temperamento sin explicación?",
  6: "Dices palabras que no querias decir, o confundes cosas con palabras incorrectas, y lo notas luego de decirlo o cuando alguien te lo dice?",
  7: "Tienes problemas sensoriales—por ejemplo, experimentas el sonido, luz o tacto de una manera diferente a como lo hacias?",
  8: "Has sido diagnosticado con deterioro cognitivo leve, y/o tienes familiares con demencia como Alzheimer?",
  9: "Tienes constantemente la barriga inflamada, con gases o con distención entre las comidas. Como si lucieras embarazada?",
  10: "Tienes diarrea o heces liquida constantemente?",
  11: "Tienes estreñimiento, las heces duras y secas, con dificultad para evacuar?",
  12: "Tienes diarrea o heces liquidas y estreñimiento de forma alterna más de lo normal?",
  13: "Sufres de acides, reflujo luego de comer, cuando has pasado mucho tiempo sin comer, y/o durante las noches?",
  14: "Tu lengua esta cubierta por una capa espesa, y/o tienes mal aliento incluso si te cepillas regularmente?",
  15: "Tienes dolores estomacales, te sientes con nauseas luego de comer, sin que puedas asociar el síntoma con una comida en especifico?",
  16: "Tienes sintomas gástricos (gases, inflamación diarrea) cuando experimentas emociones extremas como nerviosismo, temor o ansiedad?",
  17: "Retienes agua fácilmente, y/o pareciera que tu cuerpo se ve mas largo unos dias y corto otros. Tan extremos que pareciera que perdieras o ganaras peso?",
  18: "Tu peso fluctúa mas de 2 kg desde la mañana a la tarde o de un dia para otro?",
  19: "Has sido diagnosticada con alguna infección crónica como toxicidad por moho, enfermedad de lyme o infección viral?",
  20: "Sintes como si estuvieras intoxicada, incljuso si no puedes identificarlo a un síntoma específico?",
  21: "Has notado que tu piel o la parte blanca de tus ojos estan amarillas?",
  22: "Tienes sensibilidad abdominal que pareciera no estar relacionada con la alimentación, especialmente en el la parte superior del cuadrante de tu torso, o que se distribuye en la parte superior de tu espalda u hombros?",
  23: "Tienes la orina amarilla oscura o tus heces tienden flotar?",
  24: "Tienes picazón inexplicable, o erupciones de manos y pies?",
  25: "Buscas consumir dulces o sobras de comida incluso cuando has comido lo suficiente y estas llena?",
  26: "Has notado un incremento en tu apetito o tienes mas sed de lo usual?",
  27: "Tienes vision borrosa que va y viene?",
  28: "Te sientes cansada sin motivos, incluso cuando has dormido lo suficiente y notas que la fatiga es aliviada cuando comes algo?",
  29: "Te sientes mareada, temblorosa, nerviosa, irritable, “hangry” (combinacion de hambrienta y molesta) cuando no has comido por algunas horas?",
  30: "La circunferencia de tu cintura es igual o mayor que la de tu cadera?",
  31: "Se te dificulta perder peso, incluso cuando reduces calorias y/o haces ejercicio?",
  32: "Te has sacado pruebas de azucar en sangre y estuvo en 100 dl/ml o más. Y/o tienes la hemoglobina A1C superior a 5.7. Y/o estas diagnosticada prediabetica, sindrome metabolico o diabetes tipo 2?",
  33: "Tiendes a tener fatiga y dolores por las tardes, lo cual causa que estes despierta hasta tarde?",
  34: "Te sientes mareada cuando te levantas de golpe?",
  35: "Buscas usualmente consumir comida salada?",
  36: "Tienes las manos frias usualmente, incluso cuando el ambiente esta caliente o templado?",
  37: "Duermes excesivamente, o sientes que pudieras dormir todo el dia?",
  38: "Tus cejas se estan cayendo o volviendo más delgadas?",
  39: "Ha desaparecido tu deseo sexual?",
  40: "Para mujeres: Tienes dolor irregular o inusual cuando tienes la menstruacion? Para hombres: Has tenido disfunsión eréctil ultimamente?",
  41: "Te duelen las articulaciones periódicamente, en lugares aleatorios con el dolor apareciendo y desapareciendo, sin tener relación con alguna lesión?",
  42: "Tienes articulaciones hyper flexibles?",
  43: "Tienes lesiones constantemente, te doblas los tobillos, te caes, o dejas caer las cosas? Te consideras torpe? Te lesionas constantemente los tendones y ligamentos?",
  44: "Tus articulaciones se bloquean o se lesionan en ciertas posiciones?",
  45: "Te levantas con dolor en las articulaciones o músculos pero alivias el dolor al comenzar el movimiento, pero vuelve al final del dia?",
  46: "Tienes dolores de espalda y cuello crónico?",
  47: "Sufres de dolores tipo pinchazos o puñaladas, y/o las manos y pies se te durmen?",
  48: "Te duelen los masajes, especialmente en tus brazos y piernas?",
  49: "Estas experimentando reacciones extremas y obvias a algunos alimentos?—reacciones como vómitos, diarrea, dolor, reacciones alergicas en la piel o episodios neurológicos como nubla mental o ataques de pánico?",
  50: "Eres intolerante al calor o el frio, y/o tus manos o pies se tornan azul o grises cuando estan frias? Y/o tu piel, boca u ojos estan usualmente secos?",
  51: "Tienes antecedentes familiares a enfermedades autoinmunes, como artritis, lupus, esclerosis, enfermedad celiaca, o enfermedades inflamatorias intestinales?",
  52: "Tienes dolor o hinchazón de articulaciones (en el mismo lugar en ambos lados de tu cuerpo, como por ejemplo ambas manos, ambos hombros, ambos pies)?",
  53: "Tienes erupciones inexplicables, acné crónico en tu cara y cuerpo?",
  54: "Tienes extrema y constante fatiga que no puede ser aliviada durmiendo, comiendo ni con remedios?",
  55: "Tienes inexplicable debilidad muscular, o arrastras tus pies al caminar, o dejas caer cosas constantemente?",
  56: "Algunos de los sintomas anteriormente mencionados son extremos, pero desaparecen por un tiempo, luego vuelven a los dias, semanas o meses?"
 }